# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f2bb6fed6c5114c4c7fe21a60c4299b163b9df95182becf60440d342643921fc8c30143ce537262e4711e6b4fb88aa2b303e8c697b40ac86e10f2962a9c744a

test:
  secret_key_base: 7a0beeb7be4c93ab7d8439f769961664d5d359824d35df8ea567a2ef18ba95f04516141f78881ee4e6ef5476ac7818a39b0d02b0beac3a31c96b41fa6b3e8a76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
