# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


u1 = User.create(name: "Dave Hollar", email: "dave@aol.com", password: "password")
u2 = User.create(name: "Bob Barker", email: "bob@aol.com", password: "password")
u3 = User.create(name: "Robbie Johnson", email: "robbie@yahoo.com", password: "password")


p1 = Post.new(title: "Dolorem ipsum", content: "So much to say hey hey hey", user: u1)
p1.content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras at varius mi. Nam non eleifend tortor. Mauris accumsan lorem elit, eget rhoncus nunc gravida porta. Etiam facilisis neque ac ipsum eleifend lacinia. Duis tempor id ante ut consequat. Nullam at pretium lectus, quis tincidunt risus. Nullam nibh lacus, vulputate vel sodales nec, sagittis at purus. Sed et congue libero. Etiam maximus, elit quis egestas tempus, nisi nunc ultrices magna, vitae convallis dolor nisl non purus. Morbi volutpat elit nibh, id posuere ante accumsan vitae. Etiam a lectus eu risus fermentum suscipit vulputate et turpis. Fusce pulvinar, elit non ultrices pharetra, nibh nisl cursus tellus, a placerat est diam eu turpis. Phasellus et luctus eros, et finibus turpis. Praesent massa enim, congue sed hendrerit nec, porta vitae sem. Duis molestie a sapien id pretium. Integer euismod metus laoreet metus aliquam rutrum id a lorem. Aliquam eget accumsan arcu. Praesent arcu turpis, consequat nec sodales vel, dictum quis lectus. Maecenas sodales non dolor vel rutrum. Cras eu consectetur felis, vitae facilisis felis. Aenean bibendum egestas purus maximus dapibus."
p1.save

p2 = Post.new(title: "Neque porro quisquam", user: u3)
p2.content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed ipsum egestas, faucibus tellus a, semper justo. Nam rutrum arcu auctor erat luctus ultrices. Pellentesque ornare augue vel lectus dictum, eu pharetra justo dignissim. Sed finibus ex lobortis sem tristique egestas. Ut eu quam porttitor, ornare lorem eget, interdum quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dignissim nulla sit amet quam sagittis venenatis. Vestibulum congue lacus felis, id tristique urna imperdiet vel. Sed sollicitudin quis ligula non fermentum. Ut sollicitudin, tellus ut ultricies egestas, arcu est ultricies sem, posuere sagittis tellus lorem vel sapien. In sollicitudin sapien nec aliquam vehicula. Curabitur convallis vestibulum nunc vel lacinia. Sed gravida nisi interdum vestibulum tincidunt. Maecenas eget odio sed sem rutrum vestibulum eget in magna. Sed eu consectetur risus, eget fermentum eros. Phasellus sagittis enim at sapien venenatis, tempor tincidunt velit gravida. Nam commodo purus id nunc cursus vulputate. Quisque ultrices vel magna in iaculis. Integer non porttitor turpis."
p2.save

p3 = Post.new(title: "Adipisci velit quia dolor", content: "Bodda bing badda boom!", user: u2)
p3.content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In leo risus, sodales a mollis nec, iaculis non arcu. Nunc varius odio mollis lectus lacinia commodo. Nunc sit amet vulputate massa, nec varius magna. Mauris bibendum est nec aliquet tempus. Sed sodales nunc id rutrum maximus. Duis non vestibulum augue. Pellentesque sed elit id ipsum venenatis feugiat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam non nibh nec magna ullamcorper iaculis quis sed magna. Nullam rhoncus tortor augue. Cras volutpat vestibulum ante nec molestie. Integer non placerat mauris. Duis justo nunc, convallis tincidunt posuere a, porta non lacus. Donec in elit in urna viverra pharetra. Nullam leo tellus, dignissim vulputate augue sed, sagittis auctor quam. Vivamus blandit iaculis velit, quis eleifend tortor mollis sed. In nec mollis mi. Quisque suscipit risus quis elit laoreet, quis scelerisque nisi vehicula. Nunc sit amet lorem convallis, posuere lorem eu, imperdiet augue. Phasellus a est laoreet, convallis est et, ornare sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem eros, facilisis vel dictum non, ultrices eu enim."
p3.save

p4 = Post.new(title: "Quisque ex turpis",  user: u1)
p4.content = "Mauris eget dictum nibh, vel ultricies erat. Nunc interdum neque risus, in pharetra mauris ornare sit amet. Aenean gravida odio id nibh fermentum, ac finibus velit tincidunt. Integer et lorem et risus egestas dictum. Quisque malesuada dolor pulvinar, iaculis nibh ac, placerat arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris quis finibus tortor, in blandit dolor. In placerat, eros vitae fermentum porttitor, tellus massa malesuada magna, quis faucibus velit ligula sit amet ligula. Pellentesque sollicitudin, libero eu porta sagittis, orci velit ullamcorper felis, sed malesuada nunc mi vitae lacus. Quisque ex turpis, aliquam ultricies sapien fermentum, finibus mollis metus. Donec nibh sapien, dapibus vel nulla et, imperdiet consectetur neque. Nulla nec maximus lacus. Sed massa mi, egestas at fringilla eget, efficitur vitae purus. Suspendisse bibendum ex condimentum condimentum lacinia. Mauris semper, est id blandit eleifend, leo elit ultricies lacus, a consectetur lorem sem semper urna. Morbi iaculis, velit eu porta sagittis, mauris dui fringilla nunc, at iaculis arcu odio quis ex. Praesent tristique dolor urna, ut ullamcorper dui suscipit nec. Nunc sit amet magna at dolor ultricies pellentesque. Pellentesque sit amet lorem eu est convallis viverra. Pellentesque vel sollicitudin nisi."
p4.save

p5 = Post.new(title: "Dolorem ipsum quia", user: u3)
p5.content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse in pellentesque dolor, pellentesque tempus nibh. Ut eu velit ac quam condimentum gravida id at lectus. Duis erat nisl, lobortis vel ullamcorper sed, euismod nec turpis. Fusce mauris libero, vulputate eu purus vitae, eleifend rhoncus mauris. Sed a auctor nisl. Donec sit amet augue dui. Maecenas in arcu at tortor porttitor sollicitudin. Donec ligula augue, rutrum a varius ut, fermentum ac mi. Quisque commodo, massa quis posuere viverra, mi sem tempor dolor, sit amet ultricies elit felis nec massa. Integer eu lorem at ipsum malesuada fringilla eu sed lacus. Fusce scelerisque vitae massa at luctus. Donec eget volutpat augue, vel congue quam. Nullam pretium, turpis sed ornare egestas, velit mauris consectetur mauris, sed imperdiet tellus orci non arcu. Sed malesuada volutpat lacus, et dictum sem tristique vitae. Donec in ex tempus, ultrices risus in, pulvinar ex. Curabitur nec metus at sapien interdum lobortis vel non tellus. Pellentesque nec neque tincidunt, vehicula turpis nec, auctor erat. Vestibulum id tincidunt felis, id convallis nulla. Maecenas consequat eu neque a tempus. Donec tincidunt velit in lectus laoreet euismod. In ullamcorper magna odio, in fermentum sem interdum at. Vestibulum et iaculis lacus. Fusce mollis suscipit pulvinar. Curabitur fermentum felis at felis ornare lobortis quis egestas risus. Etiam faucibus nunc efficitur risus accumsan vulputate. Etiam dui justo, pulvinar in ante et, accumsan auctor erat. Aliquam efficitur sapien dolor, et vulputate nibh cursus non. Praesent vitae mi porta, rhoncus lacus non, porttitor eros. Nunc rhoncus cursus efficitur. Donec nisi diam, gravida a cursus vel, mattis ut sem."
p5.save
